### ISSUE TITLE
planning download: opportunity score in xls does not match values in html

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#224]
To investigate. It might just be a contextual opportunity vs. reference opportunity being used.

**Comment by smirolo** [comment]
The previous commit should fix this issue. I am closing. Please re-open and provide a section where mismatch happens in case it still does. Thank you.

**Comment by deborabonner** [comment]
mismatch remains. see epc-procurement

**Comment by smirolo** [comment]
Previous commit uses numbers in the correct column (i.e. same as used in html).

**Comment by deborabonner** [comment]
The opportunity score that I see in Tamerin's EPC improvement list still does not match the opportunity score on the TSP website in the "Planning" section. See attached. 
[improvements-20180510.xlsx](https://github.com/djaodjin/envconnect/files/1992673/improvements-20180510.xlsx)

**Comment by smirolo** [comment]
The server had not been restarted, hence the changes did not show in production :(.
Server restarted. Scores match as expected.
